#ifndef CORRIDOR_NAVIGATOR_HPP
#define CORRIDOR_NAVIGATOR_HPP

#include <vector>
#include <cmath>

#include "rclcpp/rclcpp.hpp"
#include "sensor_msgs/msg/laser_scan.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "geometry_msgs/msg/pose_with_covariance_stamped.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "rclcpp_action/rclcpp_action.hpp"
#include "nav2_msgs/action/navigate_to_pose.hpp"

struct Point2D
{
  float x;
  float y;
};

class CorridorNavigator : public rclcpp::Node
{
public:
/**
 * @brief ROS2 node for detecting and navigating through corridors using LaserScan data.
 */
  CorridorNavigator();

private:
  bool in_corridor_, nav_off_;
  rclcpp::Subscription<sensor_msgs::msg::LaserScan>::SharedPtr scan_sub_;
  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr odom_sub_;
  rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr vel_pub_;
  rclcpp::Publisher<geometry_msgs::msg::PoseWithCovarianceStamped>::SharedPtr initial_pose_pub_;
  rclcpp_action::Client<nav2_msgs::action::NavigateToPose>::SharedPtr stop_nav_client_;

/**
 * @brief LaserScan callback.
 * Extracts left/right points, performs linear regression, detects corridor,
 * and publishes velocity commands if corridor is detected.
 * @param msg LaserScan input message
 */
  void scanCallback(const sensor_msgs::msg::LaserScan::SharedPtr msg);

/**
 * @brief Odometry callback.
 * When exiting a corridor, republishes robot pose to restart Nav2 navigation.
 *
 * @param msg Odometry input message
 */
  void odomCallback(const nav_msgs::msg::Odometry::SharedPtr msg);

/**
 * @brief Stops Nav2 navigation by canceling all active goals.
 */
  void stopNavigation();

/**
 * @brief Publishes a zero velocity command to stop the robot.
 */
  void selfStop();
    
/**
* @brief compute the slope of the linear regression line generated by the set of points
* @param points 2D points vector
* @return slope
*/
  float regressionSlope(const std::vector<Point2D>& points);

};

#endif // CORRIDOR_NAVIGATOR_HPP